theme: jekyll-theme-cayman
title: Chiziingiin's homepage
description: The website of Chiziingiin Information Technology Research Institute!
#自定义404提示信息,出现错误时, 直接抛出异常
mvc:
  throw-exception-if-no-handler-found: true
#不要为我们工程中的资源文件建立映射
resources:
  add-mappings: false
permalink: /error.html